version: '3.4'

services:
  vibechat.web:
    build:
      context: .
      dockerfile: Vibechat.Web/Dockerfile
    ports:
     - "443:443"
    depends_on:
     - "vibechat.db"
    networks:
      - vibechat-network

  vibechat.db:
    container_name: 'vibechat.db'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<Your password>
    networks:
      - vibechat-network

networks:
  vibechat-network:
    driver: bridge